DynamicLoopGoogleMaps/Controllers/MapController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using DynamicLoopGoogleMaps.Domain;
using DynamicLoopGoogleMaps.Domain.Repositories;
using DynamicLoopGoogleMaps.Models.Models;

namespace DynamicLoopGoogleMaps.Controllers
{
    public class MapController : Controller
    {
        private readonly IBookStoreRepository _bookStoreRepository;
        private readonly IBookRepository _bookRepository;

        public MapController(IBookStoreRepository bookStoreRepository, IBookRepository bookRepository)
        {
            _bookStoreRepository = bookStoreRepository;
            _bookRepository = bookRepository;
        }

        public ActionResult Index()
        {
            var bookStores = _bookStoreRepository.GetAll();
            var model = Mapper.Map<IEnumerable<BookStore>, MapModel>(bookStores);
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(string search)
        {
            var books = _bookRepository.Search(search);
            var model = Mapper.Map<IEnumerable<BookStore>, MapModel>(books.SelectMany(book => book.BookStores).Distinct());
            return View(model);
        }
    }

}

DynamicLoopGoogleMaps/Views/Map/Index.cshtml
@model DynamicLoopGoogleMaps.Models.Models.MapModel
@section head{
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <script>
        var map;

        function initialize() {
            var mapOptions = {
                zoom: 12,
                center: new google.maps.LatLng(51.506285, -0.094242),
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            map = new google.maps.Map(document.getElementById('mapCanvas'), mapOptions);

            var locationArray = [@string.Join(", ", Model.BookStores.Select(model => string.Format("new google.maps.LatLng({0}, {1})", model.Latitude, model.Longitude)).ToList())];
            var locationNameArray = [@Html.Raw(string.Join(", ", Model.BookStores.Select(model => string.Format("\"{0}\"", model.Name)).ToList()))];
            
            for (var coord in locationArray) {
                new google.maps.Marker({
                    position: locationArray[coord],
                    map: map,
                    title: locationNameArray[coord]
                });
            }
        }
        
        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
}
@using (Html.BeginForm("Index", "Map", FormMethod.Post))
{
    <div style="text-align: center">
        <label style="font-size: 1.2em">Search a book by an Title, ISBN, Author and find the bookstores where it's available
            <input type="text" style="font-size: 1em" name="search" /></label> <input type="submit" value="Go" style="font-size: 1.2em"/>
    </div>
}
<div id="mapCanvas"></div>