DynamicLoopGoogleMaps/Controllers/AuthorsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using DynamicLoopGoogleMaps.Common.Extensions;
using DynamicLoopGoogleMaps.Domain;
using DynamicLoopGoogleMaps.Domain.Repositories;
using DynamicLoopGoogleMaps.Models.Models;

namespace DynamicLoopGoogleMaps.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly IAuthorRepository _authorRepository;

        public AuthorsController(IAuthorRepository authorRepository)
        {
            _authorRepository = authorRepository;
        }

        public ActionResult Add()
        {
            return View("Edit", new AuthorModel
                                                  {
                                                      IsEditMode = false
                                                  });
        }

        public ActionResult Edit(int id)
        {
            var author = _authorRepository.Get(id);
            if (author == null)
                return RedirectToAction("Index");
            
            var model = Mapper.Map<Author, AuthorModel>(author);
            model.IsEditMode = true;
            return View(model);
        }

        public ActionResult Index(AuthorsListSuccessMessage message = AuthorsListSuccessMessage.None)
        {
            var authors = _authorRepository.GetAll();

            var model = Mapper.Map<IEnumerable<Author>, AuthorsListModel>(authors);
            if (message != AuthorsListSuccessMessage.None)
                model.SuccessMessage = message.GetDescriptionAttributeValue();

            return View(model);
        }

        [HttpPost]
        public ActionResult Add(AuthorModel model)
        {
            if (ModelState.IsValid)
            {
                var author = Mapper.Map<AuthorModel, Author>(model);
                _authorRepository.Insert(author);
                return RedirectToAction("Index", new { message = (int)AuthorsListSuccessMessage.AuthorAddedSuccesfully });
            }
            model.IsEditMode = false;
            return View("Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(AuthorModel model)
        {
            if (ModelState.IsValid)
            {
                var author = _authorRepository.Get(model.Id);
                if (author == null)
                    return RedirectToAction("Index");
                author = Mapper.Map(model, author);
                _authorRepository.Save(author);
                return RedirectToAction("Index", new { message = (int)AuthorsListSuccessMessage.AuthorEditedSuccesfully });
            }
            model.IsEditMode = true;
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            var author = _authorRepository.Get(id);
            if (author == null)
                return RedirectToAction("Index");
            if (author.Books.Any())
                return RedirectToAction("Index", new { message = (int)AuthorsListSuccessMessage.AuthorNotDeletedSuccesfully });
            _authorRepository.Delete(author);
            return RedirectToAction("Index", new { message = (int)AuthorsListSuccessMessage.AuthorDeletedSuccesfully });
        }
    }
}

DynamicLoopGoogleMaps/Views/Authors/Edit.cshtml
@model DynamicLoopGoogleMaps.Models.Models.AuthorModel
@{
    ViewBag.Title = GetTitle();
}
@functions{
    public string GetTitle()
    {
        return Model.IsEditMode ? "Edit an author" : "Add an author";
    }

    public string GetPostAction()
    {
        return Model.IsEditMode ? "Edit" : "Add";
    }
}
<h2>@GetTitle()</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<div class="validation-error" >
    @Html.ValidationSummary(true,"The author was not saved. See below for more details.")
</div>

@using(Html.BeginForm(GetPostAction(), "Authors", FormMethod.Post)) 
{
<div>
    <fieldset>
        <legend>Author Information</legend>
        @Html.HiddenFor(model => model.Id)
        <div class="editor-label">
            @Html.LabelFor(m => m.FirstName)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.FirstName)
            @Html.ValidationMessageFor(m => m.FirstName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(m => m.LastName)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.LastName)
            @Html.ValidationMessageFor(m => m.LastName)
        </div>
        <p>
            <a href="/Authors/" class="link-button">Cancel</a> <a href="#" class="link-button"
                onclick="if ($(document.forms[0]).valid()) { document.forms[0].submit(); return false; }">
                @GetPostAction()</a>
        </p>
    </fieldset>
</div>
} 

DynamicLoopGoogleMaps/Views/Authors/Index.cshtml
@model DynamicLoopGoogleMaps.Models.Models.AuthorsListModel
@if (!string.IsNullOrEmpty(Model.SuccessMessage))
{
        <div class="success" >
            @Model.SuccessMessage
        </div>
}
<div style="text-align: left">
    <a href="/Authors/Add" class="link-button">Add an author</a>
</div>
<div style="padding-top: 20px">
    @if (Model.Authors.Any())
    {
        <table width="100%">
            <thead>
                <tr>
                    <th>Full name</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var author in Model.Authors)
                {
                    <tr>
                        <td>@author.FullName</td>
                        <td style="text-align: center"><a href="/Authors/Edit/@author.Id" class="link-button">Edit</a></td>
                        <td style="text-align: center"><a href="/Authors/Delete/@author.Id" class="link-button">Delete</a></td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="error" >
            no authors found
        </div>
    }
</div>