DynamicLoopGoogleMaps/Controllers/BookStoresController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using DynamicLoopGoogleMaps.Common.Extensions;
using DynamicLoopGoogleMaps.Domain;
using DynamicLoopGoogleMaps.Domain.Repositories;
using DynamicLoopGoogleMaps.Models.Models;

namespace DynamicLoopGoogleMaps.Controllers
{
    public class BookStoresController : Controller
    {
        private readonly IBookStoreRepository _bookStoreRepository;
        private readonly IBookRepository _bookRepository;

        public BookStoresController(IBookStoreRepository bookStoreRepository, IBookRepository bookRepository)
        {
            _bookStoreRepository = bookStoreRepository;
            _bookRepository = bookRepository;
        }

        public ActionResult Index(BookStoresListSuccessMessage message = BookStoresListSuccessMessage.None)
        {
            var bookStores = _bookStoreRepository.GetAll();

            var model = Mapper.Map<IEnumerable<BookStore>, BookStoresListModel>(bookStores);
            if (message != BookStoresListSuccessMessage.None)
                model.SuccessMessage = message.GetDescriptionAttributeValue();

            return View(model);
        }

        public ActionResult Add()
        {
            var model = new BookStoreModel
                            {
                                IsEditMode = false
                            };
            model = Mapper.Map(_bookRepository.GetAll(), model);
            return View("Edit", model);
        }

        public ActionResult Edit(int id)
        {
            var bookStore = _bookStoreRepository.Get(id);
            if (bookStore == null)
                return RedirectToAction("Index");

            var model = Mapper.Map<BookStore, BookStoreModel>(bookStore);
            model = Mapper.Map(_bookRepository.GetAll(), model);
            model.IsEditMode = true;
            return View(model);
        }

        [HttpPost]
        public ActionResult Add(BookStoreModel model)
        {
            if (ModelState.IsValid)
            {
                var bookStore = Mapper.Map<BookStoreModel, BookStore>(model);
                if (model.BooksIds != null && model.BooksIds.Any())
                    bookStore.Books = _bookRepository.GetAll().Where(book => model.BooksIds.Contains(book.Id)).ToList();
                _bookStoreRepository.Insert(bookStore);
                return RedirectToAction("Index", new { message = (int)BookStoresListSuccessMessage.BookStoreAddedSuccesfully });
            }
            return Add();
        }

        [HttpPost]
        public ActionResult Edit(BookStoreModel model)
        {
            if (ModelState.IsValid)
            {
                var bookStore = _bookStoreRepository.Get(model.Id);
                if (bookStore == null)
                    return RedirectToAction("Index");
                bookStore = Mapper.Map(model, bookStore);
                bookStore.Books.Clear();
                if (model.BooksIds != null && model.BooksIds.Any())
                    bookStore.Books = _bookRepository.GetAll().Where(book => model.BooksIds.Contains(book.Id)).ToList();
                _bookStoreRepository.Save(bookStore);
                return RedirectToAction("Index", new { message = (int)BookStoresListSuccessMessage.BookStoreEditedSuccesfully });
            }
            return Edit(model.Id);
        }

        public ActionResult Delete(int id)
        {
            var bookStore = _bookStoreRepository.Get(id);
            if (bookStore == null)
                return RedirectToAction("Index");
            _bookStoreRepository.Delete(bookStore);
            return RedirectToAction("Index", new { message = (int)BookStoresListSuccessMessage.BookStoreDeletedSuccesfully });
        }
    }
}

DynamicLoopGoogleMaps/Views/BookStores/Edit.cshtml
@model DynamicLoopGoogleMaps.Models.Models.BookStoreModel
@{
    ViewBag.Title = GetTitle();
}
@functions{
    public string GetTitle()
    {
        return Model.IsEditMode ? "Edit a book store" : "Add a book store";
    }

    public string GetPostAction()
    {
        return Model.IsEditMode ? "Edit" : "Add";
    }
}
<h2>@GetTitle()</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<div class="validation-error" >
    @Html.ValidationSummary(true, "The book store was not saved. See below for more details.")
</div>

@using (Html.BeginForm(GetPostAction(), "BookStores", FormMethod.Post))
{
    <div>
        <fieldset>
            <legend>Book store Information</legend>
            @Html.HiddenFor(model => model.Id)
            <div class="editor-label">
                @Html.LabelFor(m => m.Name)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(m => m.Name)
                @Html.ValidationMessageFor(m => m.Name)
            </div>
            <div class="editor-label">
                @Html.LabelFor(m => m.City)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(m => m.City)
                @Html.ValidationMessageFor(m => m.City)
            </div>
            <div class="editor-label">
                @Html.LabelFor(m => m.Latitude)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(m => m.Latitude)
                @Html.ValidationMessageFor(m => m.Latitude)
            </div>
            <div class="editor-label">
                @Html.LabelFor(m => m.Longitude)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(m => m.Longitude)
                @Html.ValidationMessageFor(m => m.Longitude)
            </div>
            <div class="editor-label">
                @Html.LabelFor(m => m.Books)
            </div>
            <div class="editor-field">
                @Html.ListBoxFor(m => m.BooksIds, new SelectList(Model.Books, "Id", "Title"))
                @Html.ValidationMessageFor(m => m.BooksIds)
            </div>
            <p>
                <a href="/Bookstores/" class="link-button">Cancel</a> 
                <a href="#" class="link-button" onclick="if ($(document.forms[0]).valid()) { document.forms[0].submit(); return false; }">
                    @GetPostAction()</a>
            </p>
        </fieldset>
    </div>
}

DynamicLoopGoogleMaps/Views/BookStores/Index.cshtml
@model DynamicLoopGoogleMaps.Models.Models.BookStoresListModel
@if (!string.IsNullOrEmpty(Model.SuccessMessage))
{
        <div class="success" >
            @Model.SuccessMessage
        </div>
}
<div style="text-align: left">
    <a href="/BookStores/Add" class="link-button">Add a book store</a>
</div>
<div style="padding-top: 20px">
    @if (Model.BookStores.Any())
    {
        <table width="100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>City</th>
                    <th>Books</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var bookStore in Model.BookStores)
                {
                    <tr>
                        <td>@bookStore.Name</td>
                        <td>@bookStore.City</td>
                        <td>@bookStore.Books</td>
                        <td style="text-align: center"><a href="/BookStores/Edit/@bookStore.Id" class="link-button">Edit</a></td>
                        <td style="text-align: center"><a href="/BookStores/Delete/@bookStore.Id" class="link-button">Delete</a></td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="error" >
            no book stores found
        </div>
    }
</div>